rewrite fndump

diff --git a/fndump b/fndump
--- a/fndump
+++ b/fndump
@@ -1,7 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 
-OBJ=$1
-SYM=$2
+OBJ=$1 ; shift
+SYM=$1 ; shift
+PREFIX=$@
+
+# hack
+#PREFIX="--prefix=`pwd` --prefix-strip=3"
+#PREFIX="--prefix=`pwd` --prefix-strip=5"
 
 if test -z "${OBJ}" -o -z "${SYM}" ; then
 	echo "syntax:"
@@ -11,37 +16,48 @@ if test -z "${OBJ}" -o -z "${SYM}" ; then
 	exit 1
 fi
 
-OFS=$(echo $SYM | grep '+' | sed -e 's/^.*+//;')
-SYM=$(echo $SYM | sed -e 's/+.*$//;')
+SYM=${SYM%/*}
+OFS="${SYM#*+}"
+[ "$SYM" = "$OFS" ] && OFS=0
+SYM=${SYM%+*}
+
+#echo >&2 "SYM=$SYM"
+#echo >&2 "OFS=$OFS"
 
 if ! test -r ${OBJ} ; then
 	echo "module '${OBJ}' cannot be read" >&2
 	exit 1
 fi
 
-range=$(objdump -t ${OBJ} | grep '\.text' | sort \
-        | awk '/\<gsci_scan_thread\>/ { s=strtonum("0x"$1)
-                                        l=strtonum("0x"$5)
-                                        e=s+l
-                                        printf "%x %x\n", s, e }')
+range=( $(objdump -t ${OBJ} | grep '\.text\s' | sort \
+        | awk '/\<'"$SYM"'\>/ {
+	s=strtonum("0x"$1)
+	l=strtonum("0x"$5)
+	e=s+l
+	printf "%x %x\n", s, e }') )
 
-if ! (echo ${range} | grep "[0-9a-fA-F]\+ [0-9a-fA-F]\+" > /dev/null) ; then
-	echo "cannot find symbol ${SYM} in ${OBJ}; range='${range}'" >&2
+echo "range=${range[*]}"
+
+if [ ${#range[@]} != 2 ] ; then
+	echo "cannot find symbol ${SYM} in ${OBJ}; range='${range[*]}'" >&2
 	exit 1
 fi
 
-start=$(echo ${range} | tr ' ' '\n' | head -n1)
-stop=$(echo ${range} | tr ' ' '\n' | tail -n1)
-options="--start-address=0x$start --stop-address=0x$stop"
+options="--start-address=0x${range[0]} --stop-address=0x${range[1]}"
 
-offset=$(echo ${OFS} ${range} | (read a b c ; echo $a 0x$b))
-offset=$(echo ${offset} | xargs printf "%d+%d")
-offset=$(echo ${offset} | bc | xargs printf "%x")
+base=${range[0]}
+[ ${base:0:2} = 0x ] || base=0x$base
+[ ${OFS:0:2} = 0x ] || OFS=0x${OFS:-0}
+offset=$( printf '%x' $(( ${OFS} + $base )) )
 
-cmd="objdump -S ${OBJ} ${options}"
+cmd="objdump -S -l $PREFIX ${OBJ} ${options}"
 
-echo ">>> ${OBJ} ${SYM} +${OFS} ${offset} <<<"
+echo ">>> ${OBJ} ${SYM} +${OFS} (${range[*]}) ${offset} <<<"
 echo ">>> $cmd <<<"
 
-$cmd | sed -e "s/^  \( *${offset}:.*\)$/->\1      ******/;"
+if [ -t 0 ] && [ -t 1 ] ; then
+	$cmd | vim -c "/^  \( *${offset}:.*\)$" -R -
+else
+	$cmd | sed -e "s/^  \( *${offset}:.*\)$/->\1      ******/;"
+fi
 
